// eci/retrieval/v1/retrieval.proto
// Contratto gRPC tra Query Orchestrator (client) e Retrieval & Reasoning
// Engine (server). Piano di query sincrono; mTLS STRICT via service mesh;
// SecurityContext propagato anche nei metadata gRPC dagli interceptor.
// Versionamento: package versionato (v1); campi additivi only; nessun
// riuso di tag; campi deprecati marcati reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eci/retrieval/v1/retrieval.proto

package retrievalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dominio dell'entita' (estensibilita' multi-dominio del Modulo 1).
type Domain int32

const (
	Domain_DOMAIN_UNSPECIFIED Domain = 0
	Domain_DOMAIN_CODE        Domain = 1
	Domain_DOMAIN_DOC         Domain = 2
	Domain_DOMAIN_LEGAL       Domain = 3
	Domain_DOMAIN_COMPLIANCE  Domain = 4
	Domain_DOMAIN_CONTRACT    Domain = 5
)

// Enum value maps for Domain.
var (
	Domain_name = map[int32]string{
		0: "DOMAIN_UNSPECIFIED",
		1: "DOMAIN_CODE",
		2: "DOMAIN_DOC",
		3: "DOMAIN_LEGAL",
		4: "DOMAIN_COMPLIANCE",
		5: "DOMAIN_CONTRACT",
	}
	Domain_value = map[string]int32{
		"DOMAIN_UNSPECIFIED": 0,
		"DOMAIN_CODE":        1,
		"DOMAIN_DOC":         2,
		"DOMAIN_LEGAL":       3,
		"DOMAIN_COMPLIANCE":  4,
		"DOMAIN_CONTRACT":    5,
	}
)

func (x Domain) Enum() *Domain {
	p := new(Domain)
	*p = x
	return p
}

func (x Domain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[0].Descriptor()
}

func (Domain) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[0]
}

func (x Domain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain.Descriptor instead.
func (Domain) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{0}
}

// Intento della query (dal classificatore di intento).
type QueryIntent int32

const (
	QueryIntent_QUERY_INTENT_UNSPECIFIED QueryIntent = 0
	QueryIntent_QUERY_INTENT_STRUCTURAL  QueryIntent = 1 // impact, chiamanti, dipendenze: grafo prevale
	QueryIntent_QUERY_INTENT_CONCEPTUAL  QueryIntent = 2 // ricerca semantica: vettoriale prevale
	QueryIntent_QUERY_INTENT_HYBRID      QueryIntent = 3
)

// Enum value maps for QueryIntent.
var (
	QueryIntent_name = map[int32]string{
		0: "QUERY_INTENT_UNSPECIFIED",
		1: "QUERY_INTENT_STRUCTURAL",
		2: "QUERY_INTENT_CONCEPTUAL",
		3: "QUERY_INTENT_HYBRID",
	}
	QueryIntent_value = map[string]int32{
		"QUERY_INTENT_UNSPECIFIED": 0,
		"QUERY_INTENT_STRUCTURAL":  1,
		"QUERY_INTENT_CONCEPTUAL":  2,
		"QUERY_INTENT_HYBRID":      3,
	}
)

func (x QueryIntent) Enum() *QueryIntent {
	p := new(QueryIntent)
	*p = x
	return p
}

func (x QueryIntent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryIntent) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[1].Descriptor()
}

func (QueryIntent) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[1]
}

func (x QueryIntent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryIntent.Descriptor instead.
func (QueryIntent) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{1}
}

// Tipi di arco del CPG (CodeRelation.rel_type).
type EdgeType int32

const (
	EdgeType_EDGE_TYPE_UNSPECIFIED  EdgeType = 0
	EdgeType_EDGE_TYPE_CALLS        EdgeType = 1
	EdgeType_EDGE_TYPE_IMPORTS      EdgeType = 2
	EdgeType_EDGE_TYPE_EXTENDS      EdgeType = 3
	EdgeType_EDGE_TYPE_IMPLEMENTS   EdgeType = 4
	EdgeType_EDGE_TYPE_CONTAINS     EdgeType = 5
	EdgeType_EDGE_TYPE_DEPENDS_ON   EdgeType = 6
	EdgeType_EDGE_TYPE_REFERENCES   EdgeType = 7
	EdgeType_EDGE_TYPE_OVERRIDES    EdgeType = 8
	EdgeType_EDGE_TYPE_DERIVED_FROM EdgeType = 9
	EdgeType_EDGE_TYPE_GOVERNED_BY  EdgeType = 10
	EdgeType_EDGE_TYPE_CITES        EdgeType = 11
)

// Enum value maps for EdgeType.
var (
	EdgeType_name = map[int32]string{
		0:  "EDGE_TYPE_UNSPECIFIED",
		1:  "EDGE_TYPE_CALLS",
		2:  "EDGE_TYPE_IMPORTS",
		3:  "EDGE_TYPE_EXTENDS",
		4:  "EDGE_TYPE_IMPLEMENTS",
		5:  "EDGE_TYPE_CONTAINS",
		6:  "EDGE_TYPE_DEPENDS_ON",
		7:  "EDGE_TYPE_REFERENCES",
		8:  "EDGE_TYPE_OVERRIDES",
		9:  "EDGE_TYPE_DERIVED_FROM",
		10: "EDGE_TYPE_GOVERNED_BY",
		11: "EDGE_TYPE_CITES",
	}
	EdgeType_value = map[string]int32{
		"EDGE_TYPE_UNSPECIFIED":  0,
		"EDGE_TYPE_CALLS":        1,
		"EDGE_TYPE_IMPORTS":      2,
		"EDGE_TYPE_EXTENDS":      3,
		"EDGE_TYPE_IMPLEMENTS":   4,
		"EDGE_TYPE_CONTAINS":     5,
		"EDGE_TYPE_DEPENDS_ON":   6,
		"EDGE_TYPE_REFERENCES":   7,
		"EDGE_TYPE_OVERRIDES":    8,
		"EDGE_TYPE_DERIVED_FROM": 9,
		"EDGE_TYPE_GOVERNED_BY":  10,
		"EDGE_TYPE_CITES":        11,
	}
)

func (x EdgeType) Enum() *EdgeType {
	p := new(EdgeType)
	*p = x
	return p
}

func (x EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[2].Descriptor()
}

func (EdgeType) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[2]
}

func (x EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeType.Descriptor instead.
func (EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{2}
}

// Classificazione dell'impatto (Modulo 2, §1.5).
type ImpactKind int32

const (
	ImpactKind_IMPACT_KIND_UNSPECIFIED     ImpactKind = 0
	ImpactKind_IMPACT_KIND_SYNTACTIC       ImpactKind = 1
	ImpactKind_IMPACT_KIND_BEHAVIORAL      ImpactKind = 2
	ImpactKind_IMPACT_KIND_MODULE_BOUNDARY ImpactKind = 3
)

// Enum value maps for ImpactKind.
var (
	ImpactKind_name = map[int32]string{
		0: "IMPACT_KIND_UNSPECIFIED",
		1: "IMPACT_KIND_SYNTACTIC",
		2: "IMPACT_KIND_BEHAVIORAL",
		3: "IMPACT_KIND_MODULE_BOUNDARY",
	}
	ImpactKind_value = map[string]int32{
		"IMPACT_KIND_UNSPECIFIED":     0,
		"IMPACT_KIND_SYNTACTIC":       1,
		"IMPACT_KIND_BEHAVIORAL":      2,
		"IMPACT_KIND_MODULE_BOUNDARY": 3,
	}
)

func (x ImpactKind) Enum() *ImpactKind {
	p := new(ImpactKind)
	*p = x
	return p
}

func (x ImpactKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImpactKind) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[3].Descriptor()
}

func (ImpactKind) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[3]
}

func (x ImpactKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImpactKind.Descriptor instead.
func (ImpactKind) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{3}
}

// Direzione di traversata.
type TraversalDirection int32

const (
	TraversalDirection_TRAVERSAL_DIRECTION_UNSPECIFIED TraversalDirection = 0
	TraversalDirection_TRAVERSAL_DIRECTION_FORWARD     TraversalDirection = 1 // dipendenze in uscita
	TraversalDirection_TRAVERSAL_DIRECTION_REVERSE     TraversalDirection = 2 // reverse reachability (impact)
)

// Enum value maps for TraversalDirection.
var (
	TraversalDirection_name = map[int32]string{
		0: "TRAVERSAL_DIRECTION_UNSPECIFIED",
		1: "TRAVERSAL_DIRECTION_FORWARD",
		2: "TRAVERSAL_DIRECTION_REVERSE",
	}
	TraversalDirection_value = map[string]int32{
		"TRAVERSAL_DIRECTION_UNSPECIFIED": 0,
		"TRAVERSAL_DIRECTION_FORWARD":     1,
		"TRAVERSAL_DIRECTION_REVERSE":     2,
	}
)

func (x TraversalDirection) Enum() *TraversalDirection {
	p := new(TraversalDirection)
	*p = x
	return p
}

func (x TraversalDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraversalDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[4].Descriptor()
}

func (TraversalDirection) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[4]
}

func (x TraversalDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraversalDirection.Descriptor instead.
func (TraversalDirection) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING_STATUS_UNSPECIFIED HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING_STATUS_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_SERVING_STATUS_NOT_SERVING HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVING_STATUS_DEGRADED    HealthCheckResponse_ServingStatus = 3 // una gamba di retrieval non disponibile
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNSPECIFIED",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
		3: "SERVING_STATUS_DEGRADED",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNSPECIFIED": 0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
		"SERVING_STATUS_DEGRADED":    3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_eci_retrieval_v1_retrieval_proto_enumTypes[5].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_eci_retrieval_v1_retrieval_proto_enumTypes[5]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{15, 0}
}

// Contesto di sicurezza autenticato (mai costruito dall'LLM).
// Ridondato nel body oltre che nei metadata per auditability del contratto.
type SecurityContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedRepos  []string               `protobuf:"bytes,3,rep,name=allowed_repos,json=allowedRepos,proto3" json:"allowed_repos,omitempty"`
	AclGroups     []string               `protobuf:"bytes,4,rep,name=acl_groups,json=aclGroups,proto3" json:"acl_groups,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityContext) Reset() {
	*x = SecurityContext{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityContext) ProtoMessage() {}

func (x *SecurityContext) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityContext.ProtoReflect.Descriptor instead.
func (*SecurityContext) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SecurityContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SecurityContext) GetAllowedRepos() []string {
	if x != nil {
		return x.AllowedRepos
	}
	return nil
}

func (x *SecurityContext) GetAclGroups() []string {
	if x != nil {
		return x.AclGroups
	}
	return nil
}

func (x *SecurityContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// Provenance canonica (Modulo 1): repo/path:righe@commit.
type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	StartLine     uint32                 `protobuf:"varint,3,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       uint32                 `protobuf:"varint,4,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	CommitSha     string                 `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{1}
}

func (x *Provenance) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Provenance) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Provenance) GetStartLine() uint32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Provenance) GetEndLine() uint32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Provenance) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

// Punteggi di ranking di un nodo.
type NodeScores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorScore   float64                `protobuf:"fixed64,1,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"` // similarita' Qdrant (se presente)
	RerankScore   float64                `protobuf:"fixed64,2,opt,name=rerank_score,json=rerankScore,proto3" json:"rerank_score,omitempty"` // cross-encoder (se applicato)
	ImpactScore   float64                `protobuf:"fixed64,3,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"` // GDS: w_ppr*ppr + w_prox*(1/hop) + w_bc*bc
	RrfScore      float64                `protobuf:"fixed64,4,opt,name=rrf_score,json=rrfScore,proto3" json:"rrf_score,omitempty"`          // fusione RRF k=60
	FinalScore    float64                `protobuf:"fixed64,5,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`    // rerank + beta*proximity_boost
	HopDistance   uint32                 `protobuf:"varint,6,opt,name=hop_distance,json=hopDistance,proto3" json:"hop_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScores) Reset() {
	*x = NodeScores{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScores) ProtoMessage() {}

func (x *NodeScores) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScores.ProtoReflect.Descriptor instead.
func (*NodeScores) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{2}
}

func (x *NodeScores) GetVectorScore() float64 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *NodeScores) GetRerankScore() float64 {
	if x != nil {
		return x.RerankScore
	}
	return 0
}

func (x *NodeScores) GetImpactScore() float64 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

func (x *NodeScores) GetRrfScore() float64 {
	if x != nil {
		return x.RrfScore
	}
	return 0
}

func (x *NodeScores) GetFinalScore() float64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *NodeScores) GetHopDistance() uint32 {
	if x != nil {
		return x.HopDistance
	}
	return 0
}

// Nodo recuperato (proiezione di CodeNode).
type RetrievedNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Domain        Domain                 `protobuf:"varint,2,opt,name=domain,proto3,enum=eci.retrieval.v1.Domain" json:"domain,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // Method, Class, Interface, File, ...
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`                         // summary gerarchico (RAPTOR) se richiesto
	SourceText    string                 `protobuf:"bytes,7,opt,name=source_text,json=sourceText,proto3" json:"source_text,omitempty"` // sorgente integrale solo per top-k
	Provenance    *Provenance            `protobuf:"bytes,8,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Scores        *NodeScores            `protobuf:"bytes,9,opt,name=scores,proto3" json:"scores,omitempty"`
	AstHash       string                 `protobuf:"bytes,10,opt,name=ast_hash,json=astHash,proto3" json:"ast_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedNode) Reset() {
	*x = RetrievedNode{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedNode) ProtoMessage() {}

func (x *RetrievedNode) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedNode.ProtoReflect.Descriptor instead.
func (*RetrievedNode) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievedNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RetrievedNode) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

func (x *RetrievedNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *RetrievedNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrievedNode) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *RetrievedNode) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RetrievedNode) GetSourceText() string {
	if x != nil {
		return x.SourceText
	}
	return ""
}

func (x *RetrievedNode) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *RetrievedNode) GetScores() *NodeScores {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *RetrievedNode) GetAstHash() string {
	if x != nil {
		return x.AstHash
	}
	return ""
}

type HybridSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecurityContext *SecurityContext       `protobuf:"bytes,1,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	QueryText       string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	Intent          QueryIntent            `protobuf:"varint,3,opt,name=intent,proto3,enum=eci.retrieval.v1.QueryIntent" json:"intent,omitempty"`
	Domain          Domain                 `protobuf:"varint,4,opt,name=domain,proto3,enum=eci.retrieval.v1.Domain" json:"domain,omitempty"`
	// Filtri espliciti (sottoinsieme di allowed_repos; il server ricalcola
	// comunque l'intersezione con il SecurityContext).
	Repos             []string `protobuf:"bytes,5,rep,name=repos,proto3" json:"repos,omitempty"`
	VectorLimit       uint32   `protobuf:"varint,6,opt,name=vector_limit,json=vectorLimit,proto3" json:"vector_limit,omitempty"`                     // default server: 50
	GraphLimit        uint32   `protobuf:"varint,7,opt,name=graph_limit,json=graphLimit,proto3" json:"graph_limit,omitempty"`                        // default server: 200
	TopK              uint32   `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                                          // default server: 25
	IncludeSourceText bool     `protobuf:"varint,9,opt,name=include_source_text,json=includeSourceText,proto3" json:"include_source_text,omitempty"` // sorgente integrale per i top-k
	IncludeSummaries  bool     `protobuf:"varint,10,opt,name=include_summaries,json=includeSummaries,proto3" json:"include_summaries,omitempty"`
	// Estensione additiva T4.1 (SPEC-041, port di D5 hybrid_graph_vector_search):
	// punto di ancoraggio per la traversata grafo tipizzata. Obbligatorio per
	// usare la ricerca ibrida grafo+vettoriale completa (RRF k=60 + boost di
	// prossimità topologica); un client che non lo imposta (stringa vuota)
	// continua a ricevere il comportamento T1.4 esistente (sola gamba grafo
	// full-text) — nessuna regressione sui client esistenti.
	EntryNodeId   string `protobuf:"bytes,11,opt,name=entry_node_id,json=entryNodeId,proto3" json:"entry_node_id,omitempty"`
	MaxDepth      int32  `protobuf:"varint,12,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // bound della traversata grafo (D5); >= 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{4}
}

func (x *HybridSearchRequest) GetSecurityContext() *SecurityContext {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *HybridSearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *HybridSearchRequest) GetIntent() QueryIntent {
	if x != nil {
		return x.Intent
	}
	return QueryIntent_QUERY_INTENT_UNSPECIFIED
}

func (x *HybridSearchRequest) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

func (x *HybridSearchRequest) GetRepos() []string {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *HybridSearchRequest) GetVectorLimit() uint32 {
	if x != nil {
		return x.VectorLimit
	}
	return 0
}

func (x *HybridSearchRequest) GetGraphLimit() uint32 {
	if x != nil {
		return x.GraphLimit
	}
	return 0
}

func (x *HybridSearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *HybridSearchRequest) GetIncludeSourceText() bool {
	if x != nil {
		return x.IncludeSourceText
	}
	return false
}

func (x *HybridSearchRequest) GetIncludeSummaries() bool {
	if x != nil {
		return x.IncludeSummaries
	}
	return false
}

func (x *HybridSearchRequest) GetEntryNodeId() string {
	if x != nil {
		return x.EntryNodeId
	}
	return ""
}

func (x *HybridSearchRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type HybridSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nodes []*RetrievedNode       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Diagnostica di fusione: quante gambe hanno contribuito.
	GraphCandidates   uint32 `protobuf:"varint,2,opt,name=graph_candidates,json=graphCandidates,proto3" json:"graph_candidates,omitempty"`
	VectorCandidates  uint32 `protobuf:"varint,3,opt,name=vector_candidates,json=vectorCandidates,proto3" json:"vector_candidates,omitempty"`
	VectorLegDegraded bool   `protobuf:"varint,4,opt,name=vector_leg_degraded,json=vectorLegDegraded,proto3" json:"vector_leg_degraded,omitempty"` // gamba vettoriale fallita/degradata
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{5}
}

func (x *HybridSearchResponse) GetNodes() []*RetrievedNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *HybridSearchResponse) GetGraphCandidates() uint32 {
	if x != nil {
		return x.GraphCandidates
	}
	return 0
}

func (x *HybridSearchResponse) GetVectorCandidates() uint32 {
	if x != nil {
		return x.VectorCandidates
	}
	return 0
}

func (x *HybridSearchResponse) GetVectorLegDegraded() bool {
	if x != nil {
		return x.VectorLegDegraded
	}
	return false
}

type ImpactAnalysisRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityContext   *SecurityContext       `protobuf:"bytes,1,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	EntryNodeId       string                 `protobuf:"bytes,2,opt,name=entry_node_id,json=entryNodeId,proto3" json:"entry_node_id,omitempty"`                                // nodo target (interfaccia X)
	MaxDepth          uint32                 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`                                          // bound K; default server: 4
	EdgeTypes         []EdgeType             `protobuf:"varint,4,rep,packed,name=edge_types,json=edgeTypes,proto3,enum=eci.retrieval.v1.EdgeType" json:"edge_types,omitempty"` // default: CALLS,IMPLEMENTS,EXTENDS,OVERRIDES,DEPENDS_ON,IMPORTS
	Direction         TraversalDirection     `protobuf:"varint,5,opt,name=direction,proto3,enum=eci.retrieval.v1.TraversalDirection" json:"direction,omitempty"`               // default: REVERSE
	FanoutCapPerHop   uint32                 `protobuf:"varint,6,opt,name=fanout_cap_per_hop,json=fanoutCapPerHop,proto3" json:"fanout_cap_per_hop,omitempty"`                 // cap super-nodi; 0 = default server
	MinImpactScore    float64                `protobuf:"fixed64,7,opt,name=min_impact_score,json=minImpactScore,proto3" json:"min_impact_score,omitempty"`                     // soglia di pruning
	IncludeSourceText bool                   `protobuf:"varint,8,opt,name=include_source_text,json=includeSourceText,proto3" json:"include_source_text,omitempty"`
	// Estensione additiva T4.2 (SPEC-042, ADR-0008): cap sul numero TOTALE di
	// nodi esplorati sull'INTERA traversata (concetto diverso da
	// fanout_cap_per_hop, che resta non implementato da T4.2). <= 0 -> errore
	// esplicito, nessun default silenzioso (SPEC-042 §3 scenario 6).
	MaxNodes      int32    `protobuf:"varint,9,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	Domain        Domain   `protobuf:"varint,10,opt,name=domain,proto3,enum=eci.retrieval.v1.Domain" json:"domain,omitempty"` // filtro dominio; UNSPECIFIED = nessun filtro
	Repos         []string `protobuf:"bytes,11,rep,name=repos,proto3" json:"repos,omitempty"`                                 // filtro repo (T4.2 usa solo il primo, se presente)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactAnalysisRequest) Reset() {
	*x = ImpactAnalysisRequest{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactAnalysisRequest) ProtoMessage() {}

func (x *ImpactAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactAnalysisRequest.ProtoReflect.Descriptor instead.
func (*ImpactAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{6}
}

func (x *ImpactAnalysisRequest) GetSecurityContext() *SecurityContext {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *ImpactAnalysisRequest) GetEntryNodeId() string {
	if x != nil {
		return x.EntryNodeId
	}
	return ""
}

func (x *ImpactAnalysisRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *ImpactAnalysisRequest) GetEdgeTypes() []EdgeType {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

func (x *ImpactAnalysisRequest) GetDirection() TraversalDirection {
	if x != nil {
		return x.Direction
	}
	return TraversalDirection_TRAVERSAL_DIRECTION_UNSPECIFIED
}

func (x *ImpactAnalysisRequest) GetFanoutCapPerHop() uint32 {
	if x != nil {
		return x.FanoutCapPerHop
	}
	return 0
}

func (x *ImpactAnalysisRequest) GetMinImpactScore() float64 {
	if x != nil {
		return x.MinImpactScore
	}
	return 0
}

func (x *ImpactAnalysisRequest) GetIncludeSourceText() bool {
	if x != nil {
		return x.IncludeSourceText
	}
	return false
}

func (x *ImpactAnalysisRequest) GetMaxNodes() int32 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *ImpactAnalysisRequest) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

func (x *ImpactAnalysisRequest) GetRepos() []string {
	if x != nil {
		return x.Repos
	}
	return nil
}

// Nodo impattato emesso in streaming man mano che la traversata procede.
type ImpactedNode struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Node       *RetrievedNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	ImpactKind ImpactKind             `protobuf:"varint,2,opt,name=impact_kind,json=impactKind,proto3,enum=eci.retrieval.v1.ImpactKind" json:"impact_kind,omitempty"`
	// Catena di archi dal target al nodo (per spiegabilita').
	PathEdgeTypes []EdgeType `protobuf:"varint,3,rep,packed,name=path_edge_types,json=pathEdgeTypes,proto3,enum=eci.retrieval.v1.EdgeType" json:"path_edge_types,omitempty"`
	Depth         uint32     `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactedNode) Reset() {
	*x = ImpactedNode{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactedNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactedNode) ProtoMessage() {}

func (x *ImpactedNode) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactedNode.ProtoReflect.Descriptor instead.
func (*ImpactedNode) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{7}
}

func (x *ImpactedNode) GetNode() *RetrievedNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *ImpactedNode) GetImpactKind() ImpactKind {
	if x != nil {
		return x.ImpactKind
	}
	return ImpactKind_IMPACT_KIND_UNSPECIFIED
}

func (x *ImpactedNode) GetPathEdgeTypes() []EdgeType {
	if x != nil {
		return x.PathEdgeTypes
	}
	return nil
}

func (x *ImpactedNode) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// Messaggio di avanzamento/completamento dello stream.
type ImpactProgress struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodesEmitted         uint32                 `protobuf:"varint,1,opt,name=nodes_emitted,json=nodesEmitted,proto3" json:"nodes_emitted,omitempty"`
	FrontierSize         uint32                 `protobuf:"varint,2,opt,name=frontier_size,json=frontierSize,proto3" json:"frontier_size,omitempty"`
	CurrentDepth         uint32                 `protobuf:"varint,3,opt,name=current_depth,json=currentDepth,proto3" json:"current_depth,omitempty"`
	TruncatedByFanoutCap bool                   `protobuf:"varint,4,opt,name=truncated_by_fanout_cap,json=truncatedByFanoutCap,proto3" json:"truncated_by_fanout_cap,omitempty"`
	TruncatedByDepth     bool                   `protobuf:"varint,5,opt,name=truncated_by_depth,json=truncatedByDepth,proto3" json:"truncated_by_depth,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImpactProgress) Reset() {
	*x = ImpactProgress{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactProgress) ProtoMessage() {}

func (x *ImpactProgress) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactProgress.ProtoReflect.Descriptor instead.
func (*ImpactProgress) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{8}
}

func (x *ImpactProgress) GetNodesEmitted() uint32 {
	if x != nil {
		return x.NodesEmitted
	}
	return 0
}

func (x *ImpactProgress) GetFrontierSize() uint32 {
	if x != nil {
		return x.FrontierSize
	}
	return 0
}

func (x *ImpactProgress) GetCurrentDepth() uint32 {
	if x != nil {
		return x.CurrentDepth
	}
	return 0
}

func (x *ImpactProgress) GetTruncatedByFanoutCap() bool {
	if x != nil {
		return x.TruncatedByFanoutCap
	}
	return false
}

func (x *ImpactProgress) GetTruncatedByDepth() bool {
	if x != nil {
		return x.TruncatedByDepth
	}
	return false
}

type ImpactAnalysisEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ImpactAnalysisEvent_Node
	//	*ImpactAnalysisEvent_Progress
	Event         isImpactAnalysisEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpactAnalysisEvent) Reset() {
	*x = ImpactAnalysisEvent{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpactAnalysisEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpactAnalysisEvent) ProtoMessage() {}

func (x *ImpactAnalysisEvent) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpactAnalysisEvent.ProtoReflect.Descriptor instead.
func (*ImpactAnalysisEvent) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{9}
}

func (x *ImpactAnalysisEvent) GetEvent() isImpactAnalysisEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ImpactAnalysisEvent) GetNode() *ImpactedNode {
	if x != nil {
		if x, ok := x.Event.(*ImpactAnalysisEvent_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *ImpactAnalysisEvent) GetProgress() *ImpactProgress {
	if x != nil {
		if x, ok := x.Event.(*ImpactAnalysisEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isImpactAnalysisEvent_Event interface {
	isImpactAnalysisEvent_Event()
}

type ImpactAnalysisEvent_Node struct {
	Node *ImpactedNode `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type ImpactAnalysisEvent_Progress struct {
	Progress *ImpactProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

func (*ImpactAnalysisEvent_Node) isImpactAnalysisEvent_Event() {}

func (*ImpactAnalysisEvent_Progress) isImpactAnalysisEvent_Event() {}

type GetNodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SecurityContext   *SecurityContext       `protobuf:"bytes,1,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	NodeId            string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IncludeSourceText bool                   `protobuf:"varint,3,opt,name=include_source_text,json=includeSourceText,proto3" json:"include_source_text,omitempty"`
	IncludeSummary    bool                   `protobuf:"varint,4,opt,name=include_summary,json=includeSummary,proto3" json:"include_summary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{10}
}

func (x *GetNodeRequest) GetSecurityContext() *SecurityContext {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeRequest) GetIncludeSourceText() bool {
	if x != nil {
		return x.IncludeSourceText
	}
	return false
}

func (x *GetNodeRequest) GetIncludeSummary() bool {
	if x != nil {
		return x.IncludeSummary
	}
	return false
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *RetrievedNode         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeResponse) GetNode() *RetrievedNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type ExpandNeighborsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SecurityContext *SecurityContext       `protobuf:"bytes,1,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EdgeTypes       []EdgeType             `protobuf:"varint,3,rep,packed,name=edge_types,json=edgeTypes,proto3,enum=eci.retrieval.v1.EdgeType" json:"edge_types,omitempty"`
	Direction       TraversalDirection     `protobuf:"varint,4,opt,name=direction,proto3,enum=eci.retrieval.v1.TraversalDirection" json:"direction,omitempty"`
	Depth           uint32                 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"` // default server: 1
	Limit           uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpandNeighborsRequest) Reset() {
	*x = ExpandNeighborsRequest{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandNeighborsRequest) ProtoMessage() {}

func (x *ExpandNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandNeighborsRequest.ProtoReflect.Descriptor instead.
func (*ExpandNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{12}
}

func (x *ExpandNeighborsRequest) GetSecurityContext() *SecurityContext {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *ExpandNeighborsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExpandNeighborsRequest) GetEdgeTypes() []EdgeType {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

func (x *ExpandNeighborsRequest) GetDirection() TraversalDirection {
	if x != nil {
		return x.Direction
	}
	return TraversalDirection_TRAVERSAL_DIRECTION_UNSPECIFIED
}

func (x *ExpandNeighborsRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ExpandNeighborsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ExpandNeighborsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Neighbors          []*RetrievedNode       `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	TraversedEdgeTypes []EdgeType             `protobuf:"varint,2,rep,packed,name=traversed_edge_types,json=traversedEdgeTypes,proto3,enum=eci.retrieval.v1.EdgeType" json:"traversed_edge_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExpandNeighborsResponse) Reset() {
	*x = ExpandNeighborsResponse{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandNeighborsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandNeighborsResponse) ProtoMessage() {}

func (x *ExpandNeighborsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandNeighborsResponse.ProtoReflect.Descriptor instead.
func (*ExpandNeighborsResponse) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{13}
}

func (x *ExpandNeighborsResponse) GetNeighbors() []*RetrievedNode {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *ExpandNeighborsResponse) GetTraversedEdgeTypes() []EdgeType {
	if x != nil {
		return x.TraversedEdgeTypes
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state              protoimpl.MessageState            `protogen:"open.v1"`
	Status             HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=eci.retrieval.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	GraphLegHealthy    bool                              `protobuf:"varint,2,opt,name=graph_leg_healthy,json=graphLegHealthy,proto3" json:"graph_leg_healthy,omitempty"`
	VectorLegHealthy   bool                              `protobuf:"varint,3,opt,name=vector_leg_healthy,json=vectorLegHealthy,proto3" json:"vector_leg_healthy,omitempty"`
	FulltextLegHealthy bool                              `protobuf:"varint,4,opt,name=fulltext_leg_healthy,json=fulltextLegHealthy,proto3" json:"fulltext_leg_healthy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_retrieval_v1_retrieval_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_eci_retrieval_v1_retrieval_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetGraphLegHealthy() bool {
	if x != nil {
		return x.GraphLegHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetVectorLegHealthy() bool {
	if x != nil {
		return x.VectorLegHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetFulltextLegHealthy() bool {
	if x != nil {
		return x.FulltextLegHealthy
	}
	return false
}

var File_eci_retrieval_v1_retrieval_proto protoreflect.FileDescriptor

const file_eci_retrieval_v1_retrieval_proto_rawDesc = "" +
	"\n" +
	" eci/retrieval/v1/retrieval.proto\x12\x10eci.retrieval.v1\"\xa6\x01\n" +
	"\x0fSecurityContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rallowed_repos\x18\x03 \x03(\tR\fallowedRepos\x12\x1d\n" +
	"\n" +
	"acl_groups\x18\x04 \x03(\tR\taclGroups\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"\x8d\x01\n" +
	"\n" +
	"Provenance\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"start_line\x18\x03 \x01(\rR\tstartLine\x12\x19\n" +
	"\bend_line\x18\x04 \x01(\rR\aendLine\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\"\xd6\x01\n" +
	"\n" +
	"NodeScores\x12!\n" +
	"\fvector_score\x18\x01 \x01(\x01R\vvectorScore\x12!\n" +
	"\frerank_score\x18\x02 \x01(\x01R\vrerankScore\x12!\n" +
	"\fimpact_score\x18\x03 \x01(\x01R\vimpactScore\x12\x1b\n" +
	"\trrf_score\x18\x04 \x01(\x01R\brrfScore\x12\x1f\n" +
	"\vfinal_score\x18\x05 \x01(\x01R\n" +
	"finalScore\x12!\n" +
	"\fhop_distance\x18\x06 \x01(\rR\vhopDistance\"\xf3\x02\n" +
	"\rRetrievedNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\x06domain\x18\x02 \x01(\x0e2\x18.eci.retrieval.v1.DomainR\x06domain\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1f\n" +
	"\vsource_text\x18\a \x01(\tR\n" +
	"sourceText\x12<\n" +
	"\n" +
	"provenance\x18\b \x01(\v2\x1c.eci.retrieval.v1.ProvenanceR\n" +
	"provenance\x124\n" +
	"\x06scores\x18\t \x01(\v2\x1c.eci.retrieval.v1.NodeScoresR\x06scores\x12\x19\n" +
	"\bast_hash\x18\n" +
	" \x01(\tR\aastHash\"\xf8\x03\n" +
	"\x13HybridSearchRequest\x12L\n" +
	"\x10security_context\x18\x01 \x01(\v2!.eci.retrieval.v1.SecurityContextR\x0fsecurityContext\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x125\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x1d.eci.retrieval.v1.QueryIntentR\x06intent\x120\n" +
	"\x06domain\x18\x04 \x01(\x0e2\x18.eci.retrieval.v1.DomainR\x06domain\x12\x14\n" +
	"\x05repos\x18\x05 \x03(\tR\x05repos\x12!\n" +
	"\fvector_limit\x18\x06 \x01(\rR\vvectorLimit\x12\x1f\n" +
	"\vgraph_limit\x18\a \x01(\rR\n" +
	"graphLimit\x12\x13\n" +
	"\x05top_k\x18\b \x01(\rR\x04topK\x12.\n" +
	"\x13include_source_text\x18\t \x01(\bR\x11includeSourceText\x12+\n" +
	"\x11include_summaries\x18\n" +
	" \x01(\bR\x10includeSummaries\x12\"\n" +
	"\rentry_node_id\x18\v \x01(\tR\ventryNodeId\x12\x1b\n" +
	"\tmax_depth\x18\f \x01(\x05R\bmaxDepth\"\xd5\x01\n" +
	"\x14HybridSearchResponse\x125\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1f.eci.retrieval.v1.RetrievedNodeR\x05nodes\x12)\n" +
	"\x10graph_candidates\x18\x02 \x01(\rR\x0fgraphCandidates\x12+\n" +
	"\x11vector_candidates\x18\x03 \x01(\rR\x10vectorCandidates\x12.\n" +
	"\x13vector_leg_degraded\x18\x04 \x01(\bR\x11vectorLegDegraded\"\x91\x04\n" +
	"\x15ImpactAnalysisRequest\x12L\n" +
	"\x10security_context\x18\x01 \x01(\v2!.eci.retrieval.v1.SecurityContextR\x0fsecurityContext\x12\"\n" +
	"\rentry_node_id\x18\x02 \x01(\tR\ventryNodeId\x12\x1b\n" +
	"\tmax_depth\x18\x03 \x01(\rR\bmaxDepth\x129\n" +
	"\n" +
	"edge_types\x18\x04 \x03(\x0e2\x1a.eci.retrieval.v1.EdgeTypeR\tedgeTypes\x12B\n" +
	"\tdirection\x18\x05 \x01(\x0e2$.eci.retrieval.v1.TraversalDirectionR\tdirection\x12+\n" +
	"\x12fanout_cap_per_hop\x18\x06 \x01(\rR\x0ffanoutCapPerHop\x12(\n" +
	"\x10min_impact_score\x18\a \x01(\x01R\x0eminImpactScore\x12.\n" +
	"\x13include_source_text\x18\b \x01(\bR\x11includeSourceText\x12\x1b\n" +
	"\tmax_nodes\x18\t \x01(\x05R\bmaxNodes\x120\n" +
	"\x06domain\x18\n" +
	" \x01(\x0e2\x18.eci.retrieval.v1.DomainR\x06domain\x12\x14\n" +
	"\x05repos\x18\v \x03(\tR\x05repos\"\xdc\x01\n" +
	"\fImpactedNode\x123\n" +
	"\x04node\x18\x01 \x01(\v2\x1f.eci.retrieval.v1.RetrievedNodeR\x04node\x12=\n" +
	"\vimpact_kind\x18\x02 \x01(\x0e2\x1c.eci.retrieval.v1.ImpactKindR\n" +
	"impactKind\x12B\n" +
	"\x0fpath_edge_types\x18\x03 \x03(\x0e2\x1a.eci.retrieval.v1.EdgeTypeR\rpathEdgeTypes\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\rR\x05depth\"\xe4\x01\n" +
	"\x0eImpactProgress\x12#\n" +
	"\rnodes_emitted\x18\x01 \x01(\rR\fnodesEmitted\x12#\n" +
	"\rfrontier_size\x18\x02 \x01(\rR\ffrontierSize\x12#\n" +
	"\rcurrent_depth\x18\x03 \x01(\rR\fcurrentDepth\x125\n" +
	"\x17truncated_by_fanout_cap\x18\x04 \x01(\bR\x14truncatedByFanoutCap\x12,\n" +
	"\x12truncated_by_depth\x18\x05 \x01(\bR\x10truncatedByDepth\"\x94\x01\n" +
	"\x13ImpactAnalysisEvent\x124\n" +
	"\x04node\x18\x01 \x01(\v2\x1e.eci.retrieval.v1.ImpactedNodeH\x00R\x04node\x12>\n" +
	"\bprogress\x18\x02 \x01(\v2 .eci.retrieval.v1.ImpactProgressH\x00R\bprogressB\a\n" +
	"\x05event\"\xd0\x01\n" +
	"\x0eGetNodeRequest\x12L\n" +
	"\x10security_context\x18\x01 \x01(\v2!.eci.retrieval.v1.SecurityContextR\x0fsecurityContext\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12.\n" +
	"\x13include_source_text\x18\x03 \x01(\bR\x11includeSourceText\x12'\n" +
	"\x0finclude_summary\x18\x04 \x01(\bR\x0eincludeSummary\"F\n" +
	"\x0fGetNodeResponse\x123\n" +
	"\x04node\x18\x01 \x01(\v2\x1f.eci.retrieval.v1.RetrievedNodeR\x04node\"\xaa\x02\n" +
	"\x16ExpandNeighborsRequest\x12L\n" +
	"\x10security_context\x18\x01 \x01(\v2!.eci.retrieval.v1.SecurityContextR\x0fsecurityContext\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"edge_types\x18\x03 \x03(\x0e2\x1a.eci.retrieval.v1.EdgeTypeR\tedgeTypes\x12B\n" +
	"\tdirection\x18\x04 \x01(\x0e2$.eci.retrieval.v1.TraversalDirectionR\tdirection\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\rR\x05depth\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\"\xa6\x01\n" +
	"\x17ExpandNeighborsResponse\x12=\n" +
	"\tneighbors\x18\x01 \x03(\v2\x1f.eci.retrieval.v1.RetrievedNodeR\tneighbors\x12L\n" +
	"\x14traversed_edge_types\x18\x02 \x03(\x0e2\x1a.eci.retrieval.v1.EdgeTypeR\x12traversedEdgeTypes\"\x14\n" +
	"\x12HealthCheckRequest\"\xf9\x02\n" +
	"\x13HealthCheckResponse\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.eci.retrieval.v1.HealthCheckResponse.ServingStatusR\x06status\x12*\n" +
	"\x11graph_leg_healthy\x18\x02 \x01(\bR\x0fgraphLegHealthy\x12,\n" +
	"\x12vector_leg_healthy\x18\x03 \x01(\bR\x10vectorLegHealthy\x120\n" +
	"\x14fulltext_leg_healthy\x18\x04 \x01(\bR\x12fulltextLegHealthy\"\x88\x01\n" +
	"\rServingStatus\x12\x1e\n" +
	"\x1aSERVING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVING_STATUS_SERVING\x10\x01\x12\x1e\n" +
	"\x1aSERVING_STATUS_NOT_SERVING\x10\x02\x12\x1b\n" +
	"\x17SERVING_STATUS_DEGRADED\x10\x03*\x7f\n" +
	"\x06Domain\x12\x16\n" +
	"\x12DOMAIN_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDOMAIN_CODE\x10\x01\x12\x0e\n" +
	"\n" +
	"DOMAIN_DOC\x10\x02\x12\x10\n" +
	"\fDOMAIN_LEGAL\x10\x03\x12\x15\n" +
	"\x11DOMAIN_COMPLIANCE\x10\x04\x12\x13\n" +
	"\x0fDOMAIN_CONTRACT\x10\x05*~\n" +
	"\vQueryIntent\x12\x1c\n" +
	"\x18QUERY_INTENT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17QUERY_INTENT_STRUCTURAL\x10\x01\x12\x1b\n" +
	"\x17QUERY_INTENT_CONCEPTUAL\x10\x02\x12\x17\n" +
	"\x13QUERY_INTENT_HYBRID\x10\x03*\xb3\x02\n" +
	"\bEdgeType\x12\x19\n" +
	"\x15EDGE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEDGE_TYPE_CALLS\x10\x01\x12\x15\n" +
	"\x11EDGE_TYPE_IMPORTS\x10\x02\x12\x15\n" +
	"\x11EDGE_TYPE_EXTENDS\x10\x03\x12\x18\n" +
	"\x14EDGE_TYPE_IMPLEMENTS\x10\x04\x12\x16\n" +
	"\x12EDGE_TYPE_CONTAINS\x10\x05\x12\x18\n" +
	"\x14EDGE_TYPE_DEPENDS_ON\x10\x06\x12\x18\n" +
	"\x14EDGE_TYPE_REFERENCES\x10\a\x12\x17\n" +
	"\x13EDGE_TYPE_OVERRIDES\x10\b\x12\x1a\n" +
	"\x16EDGE_TYPE_DERIVED_FROM\x10\t\x12\x19\n" +
	"\x15EDGE_TYPE_GOVERNED_BY\x10\n" +
	"\x12\x13\n" +
	"\x0fEDGE_TYPE_CITES\x10\v*\x81\x01\n" +
	"\n" +
	"ImpactKind\x12\x1b\n" +
	"\x17IMPACT_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15IMPACT_KIND_SYNTACTIC\x10\x01\x12\x1a\n" +
	"\x16IMPACT_KIND_BEHAVIORAL\x10\x02\x12\x1f\n" +
	"\x1bIMPACT_KIND_MODULE_BOUNDARY\x10\x03*{\n" +
	"\x12TraversalDirection\x12#\n" +
	"\x1fTRAVERSAL_DIRECTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRAVERSAL_DIRECTION_FORWARD\x10\x01\x12\x1f\n" +
	"\x1bTRAVERSAL_DIRECTION_REVERSE\x10\x022\xe3\x03\n" +
	"\x0fRetrievalEngine\x12]\n" +
	"\fHybridSearch\x12%.eci.retrieval.v1.HybridSearchRequest\x1a&.eci.retrieval.v1.HybridSearchResponse\x12b\n" +
	"\x0eImpactAnalysis\x12'.eci.retrieval.v1.ImpactAnalysisRequest\x1a%.eci.retrieval.v1.ImpactAnalysisEvent0\x01\x12N\n" +
	"\aGetNode\x12 .eci.retrieval.v1.GetNodeRequest\x1a!.eci.retrieval.v1.GetNodeResponse\x12f\n" +
	"\x0fExpandNeighbors\x12(.eci.retrieval.v1.ExpandNeighborsRequest\x1a).eci.retrieval.v1.ExpandNeighborsResponse\x12U\n" +
	"\x06Health\x12$.eci.retrieval.v1.HealthCheckRequest\x1a%.eci.retrieval.v1.HealthCheckResponseB6\n" +
	"\x14com.eci.retrieval.v1P\x01Z\x1ceci/retrieval/v1;retrievalv1b\x06proto3"

var (
	file_eci_retrieval_v1_retrieval_proto_rawDescOnce sync.Once
	file_eci_retrieval_v1_retrieval_proto_rawDescData []byte
)

func file_eci_retrieval_v1_retrieval_proto_rawDescGZIP() []byte {
	file_eci_retrieval_v1_retrieval_proto_rawDescOnce.Do(func() {
		file_eci_retrieval_v1_retrieval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eci_retrieval_v1_retrieval_proto_rawDesc), len(file_eci_retrieval_v1_retrieval_proto_rawDesc)))
	})
	return file_eci_retrieval_v1_retrieval_proto_rawDescData
}

var file_eci_retrieval_v1_retrieval_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_eci_retrieval_v1_retrieval_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_eci_retrieval_v1_retrieval_proto_goTypes = []any{
	(Domain)(0),                            // 0: eci.retrieval.v1.Domain
	(QueryIntent)(0),                       // 1: eci.retrieval.v1.QueryIntent
	(EdgeType)(0),                          // 2: eci.retrieval.v1.EdgeType
	(ImpactKind)(0),                        // 3: eci.retrieval.v1.ImpactKind
	(TraversalDirection)(0),                // 4: eci.retrieval.v1.TraversalDirection
	(HealthCheckResponse_ServingStatus)(0), // 5: eci.retrieval.v1.HealthCheckResponse.ServingStatus
	(*SecurityContext)(nil),                // 6: eci.retrieval.v1.SecurityContext
	(*Provenance)(nil),                     // 7: eci.retrieval.v1.Provenance
	(*NodeScores)(nil),                     // 8: eci.retrieval.v1.NodeScores
	(*RetrievedNode)(nil),                  // 9: eci.retrieval.v1.RetrievedNode
	(*HybridSearchRequest)(nil),            // 10: eci.retrieval.v1.HybridSearchRequest
	(*HybridSearchResponse)(nil),           // 11: eci.retrieval.v1.HybridSearchResponse
	(*ImpactAnalysisRequest)(nil),          // 12: eci.retrieval.v1.ImpactAnalysisRequest
	(*ImpactedNode)(nil),                   // 13: eci.retrieval.v1.ImpactedNode
	(*ImpactProgress)(nil),                 // 14: eci.retrieval.v1.ImpactProgress
	(*ImpactAnalysisEvent)(nil),            // 15: eci.retrieval.v1.ImpactAnalysisEvent
	(*GetNodeRequest)(nil),                 // 16: eci.retrieval.v1.GetNodeRequest
	(*GetNodeResponse)(nil),                // 17: eci.retrieval.v1.GetNodeResponse
	(*ExpandNeighborsRequest)(nil),         // 18: eci.retrieval.v1.ExpandNeighborsRequest
	(*ExpandNeighborsResponse)(nil),        // 19: eci.retrieval.v1.ExpandNeighborsResponse
	(*HealthCheckRequest)(nil),             // 20: eci.retrieval.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 21: eci.retrieval.v1.HealthCheckResponse
}
var file_eci_retrieval_v1_retrieval_proto_depIdxs = []int32{
	0,  // 0: eci.retrieval.v1.RetrievedNode.domain:type_name -> eci.retrieval.v1.Domain
	7,  // 1: eci.retrieval.v1.RetrievedNode.provenance:type_name -> eci.retrieval.v1.Provenance
	8,  // 2: eci.retrieval.v1.RetrievedNode.scores:type_name -> eci.retrieval.v1.NodeScores
	6,  // 3: eci.retrieval.v1.HybridSearchRequest.security_context:type_name -> eci.retrieval.v1.SecurityContext
	1,  // 4: eci.retrieval.v1.HybridSearchRequest.intent:type_name -> eci.retrieval.v1.QueryIntent
	0,  // 5: eci.retrieval.v1.HybridSearchRequest.domain:type_name -> eci.retrieval.v1.Domain
	9,  // 6: eci.retrieval.v1.HybridSearchResponse.nodes:type_name -> eci.retrieval.v1.RetrievedNode
	6,  // 7: eci.retrieval.v1.ImpactAnalysisRequest.security_context:type_name -> eci.retrieval.v1.SecurityContext
	2,  // 8: eci.retrieval.v1.ImpactAnalysisRequest.edge_types:type_name -> eci.retrieval.v1.EdgeType
	4,  // 9: eci.retrieval.v1.ImpactAnalysisRequest.direction:type_name -> eci.retrieval.v1.TraversalDirection
	0,  // 10: eci.retrieval.v1.ImpactAnalysisRequest.domain:type_name -> eci.retrieval.v1.Domain
	9,  // 11: eci.retrieval.v1.ImpactedNode.node:type_name -> eci.retrieval.v1.RetrievedNode
	3,  // 12: eci.retrieval.v1.ImpactedNode.impact_kind:type_name -> eci.retrieval.v1.ImpactKind
	2,  // 13: eci.retrieval.v1.ImpactedNode.path_edge_types:type_name -> eci.retrieval.v1.EdgeType
	13, // 14: eci.retrieval.v1.ImpactAnalysisEvent.node:type_name -> eci.retrieval.v1.ImpactedNode
	14, // 15: eci.retrieval.v1.ImpactAnalysisEvent.progress:type_name -> eci.retrieval.v1.ImpactProgress
	6,  // 16: eci.retrieval.v1.GetNodeRequest.security_context:type_name -> eci.retrieval.v1.SecurityContext
	9,  // 17: eci.retrieval.v1.GetNodeResponse.node:type_name -> eci.retrieval.v1.RetrievedNode
	6,  // 18: eci.retrieval.v1.ExpandNeighborsRequest.security_context:type_name -> eci.retrieval.v1.SecurityContext
	2,  // 19: eci.retrieval.v1.ExpandNeighborsRequest.edge_types:type_name -> eci.retrieval.v1.EdgeType
	4,  // 20: eci.retrieval.v1.ExpandNeighborsRequest.direction:type_name -> eci.retrieval.v1.TraversalDirection
	9,  // 21: eci.retrieval.v1.ExpandNeighborsResponse.neighbors:type_name -> eci.retrieval.v1.RetrievedNode
	2,  // 22: eci.retrieval.v1.ExpandNeighborsResponse.traversed_edge_types:type_name -> eci.retrieval.v1.EdgeType
	5,  // 23: eci.retrieval.v1.HealthCheckResponse.status:type_name -> eci.retrieval.v1.HealthCheckResponse.ServingStatus
	10, // 24: eci.retrieval.v1.RetrievalEngine.HybridSearch:input_type -> eci.retrieval.v1.HybridSearchRequest
	12, // 25: eci.retrieval.v1.RetrievalEngine.ImpactAnalysis:input_type -> eci.retrieval.v1.ImpactAnalysisRequest
	16, // 26: eci.retrieval.v1.RetrievalEngine.GetNode:input_type -> eci.retrieval.v1.GetNodeRequest
	18, // 27: eci.retrieval.v1.RetrievalEngine.ExpandNeighbors:input_type -> eci.retrieval.v1.ExpandNeighborsRequest
	20, // 28: eci.retrieval.v1.RetrievalEngine.Health:input_type -> eci.retrieval.v1.HealthCheckRequest
	11, // 29: eci.retrieval.v1.RetrievalEngine.HybridSearch:output_type -> eci.retrieval.v1.HybridSearchResponse
	15, // 30: eci.retrieval.v1.RetrievalEngine.ImpactAnalysis:output_type -> eci.retrieval.v1.ImpactAnalysisEvent
	17, // 31: eci.retrieval.v1.RetrievalEngine.GetNode:output_type -> eci.retrieval.v1.GetNodeResponse
	19, // 32: eci.retrieval.v1.RetrievalEngine.ExpandNeighbors:output_type -> eci.retrieval.v1.ExpandNeighborsResponse
	21, // 33: eci.retrieval.v1.RetrievalEngine.Health:output_type -> eci.retrieval.v1.HealthCheckResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_eci_retrieval_v1_retrieval_proto_init() }
func file_eci_retrieval_v1_retrieval_proto_init() {
	if File_eci_retrieval_v1_retrieval_proto != nil {
		return
	}
	file_eci_retrieval_v1_retrieval_proto_msgTypes[9].OneofWrappers = []any{
		(*ImpactAnalysisEvent_Node)(nil),
		(*ImpactAnalysisEvent_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eci_retrieval_v1_retrieval_proto_rawDesc), len(file_eci_retrieval_v1_retrieval_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eci_retrieval_v1_retrieval_proto_goTypes,
		DependencyIndexes: file_eci_retrieval_v1_retrieval_proto_depIdxs,
		EnumInfos:         file_eci_retrieval_v1_retrieval_proto_enumTypes,
		MessageInfos:      file_eci_retrieval_v1_retrieval_proto_msgTypes,
	}.Build()
	File_eci_retrieval_v1_retrieval_proto = out.File
	file_eci_retrieval_v1_retrieval_proto_goTypes = nil
	file_eci_retrieval_v1_retrieval_proto_depIdxs = nil
}
