// eci/retrieval/v1/retrieval.proto
// Contratto gRPC tra Query Orchestrator (client) e Retrieval & Reasoning
// Engine (server). Piano di query sincrono; mTLS STRICT via service mesh;
// SecurityContext propagato anche nei metadata gRPC dagli interceptor.
// Versionamento: package versionato (v1); campi additivi only; nessun
// riuso di tag; campi deprecati marcati reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: eci/retrieval/v1/retrieval.proto

package retrievalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RetrievalEngine_HybridSearch_FullMethodName    = "/eci.retrieval.v1.RetrievalEngine/HybridSearch"
	RetrievalEngine_ImpactAnalysis_FullMethodName  = "/eci.retrieval.v1.RetrievalEngine/ImpactAnalysis"
	RetrievalEngine_GetNode_FullMethodName         = "/eci.retrieval.v1.RetrievalEngine/GetNode"
	RetrievalEngine_ExpandNeighbors_FullMethodName = "/eci.retrieval.v1.RetrievalEngine/ExpandNeighbors"
	RetrievalEngine_Health_FullMethodName          = "/eci.retrieval.v1.RetrievalEngine/Health"
)

// RetrievalEngineClient is the client API for RetrievalEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RetrievalEngineClient interface {
	// Ricerca ibrida grafo+vettoriale con fusione RRF (k=60). Idempotente:
	// eleggibile a retry/hedging secondo la policy del canale.
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// Impact analysis con streaming server-side dei nodi impattati.
	// Idempotente (sola lettura); la deadline propagata copre l'intero stream.
	ImpactAnalysis(ctx context.Context, in *ImpactAnalysisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImpactAnalysisEvent], error)
	// Lookup puntuale di un CodeNode (tool get_node).
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// Espansione tipizzata dei vicini (tool get_callers/get_callees/
	// expand_dependencies, parametrizzati da edge_types + direction).
	ExpandNeighbors(ctx context.Context, in *ExpandNeighborsRequest, opts ...grpc.CallOption) (*ExpandNeighborsResponse, error)
	// Liveness/readiness con dettaglio delle gambe di retrieval.
	Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type retrievalEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrievalEngineClient(cc grpc.ClientConnInterface) RetrievalEngineClient {
	return &retrievalEngineClient{cc}
}

func (c *retrievalEngineClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, RetrievalEngine_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalEngineClient) ImpactAnalysis(ctx context.Context, in *ImpactAnalysisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ImpactAnalysisEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RetrievalEngine_ServiceDesc.Streams[0], RetrievalEngine_ImpactAnalysis_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImpactAnalysisRequest, ImpactAnalysisEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RetrievalEngine_ImpactAnalysisClient = grpc.ServerStreamingClient[ImpactAnalysisEvent]

func (c *retrievalEngineClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, RetrievalEngine_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalEngineClient) ExpandNeighbors(ctx context.Context, in *ExpandNeighborsRequest, opts ...grpc.CallOption) (*ExpandNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpandNeighborsResponse)
	err := c.cc.Invoke(ctx, RetrievalEngine_ExpandNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalEngineClient) Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, RetrievalEngine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalEngineServer is the server API for RetrievalEngine service.
// All implementations must embed UnimplementedRetrievalEngineServer
// for forward compatibility.
type RetrievalEngineServer interface {
	// Ricerca ibrida grafo+vettoriale con fusione RRF (k=60). Idempotente:
	// eleggibile a retry/hedging secondo la policy del canale.
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// Impact analysis con streaming server-side dei nodi impattati.
	// Idempotente (sola lettura); la deadline propagata copre l'intero stream.
	ImpactAnalysis(*ImpactAnalysisRequest, grpc.ServerStreamingServer[ImpactAnalysisEvent]) error
	// Lookup puntuale di un CodeNode (tool get_node).
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// Espansione tipizzata dei vicini (tool get_callers/get_callees/
	// expand_dependencies, parametrizzati da edge_types + direction).
	ExpandNeighbors(context.Context, *ExpandNeighborsRequest) (*ExpandNeighborsResponse, error)
	// Liveness/readiness con dettaglio delle gambe di retrieval.
	Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedRetrievalEngineServer()
}

// UnimplementedRetrievalEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrievalEngineServer struct{}

func (UnimplementedRetrievalEngineServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedRetrievalEngineServer) ImpactAnalysis(*ImpactAnalysisRequest, grpc.ServerStreamingServer[ImpactAnalysisEvent]) error {
	return status.Error(codes.Unimplemented, "method ImpactAnalysis not implemented")
}
func (UnimplementedRetrievalEngineServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedRetrievalEngineServer) ExpandNeighbors(context.Context, *ExpandNeighborsRequest) (*ExpandNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExpandNeighbors not implemented")
}
func (UnimplementedRetrievalEngineServer) Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRetrievalEngineServer) mustEmbedUnimplementedRetrievalEngineServer() {}
func (UnimplementedRetrievalEngineServer) testEmbeddedByValue()                         {}

// UnsafeRetrievalEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrievalEngineServer will
// result in compilation errors.
type UnsafeRetrievalEngineServer interface {
	mustEmbedUnimplementedRetrievalEngineServer()
}

func RegisterRetrievalEngineServer(s grpc.ServiceRegistrar, srv RetrievalEngineServer) {
	// If the following call panics, it indicates UnimplementedRetrievalEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrievalEngine_ServiceDesc, srv)
}

func _RetrievalEngine_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalEngineServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalEngine_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalEngineServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalEngine_ImpactAnalysis_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImpactAnalysisRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RetrievalEngineServer).ImpactAnalysis(m, &grpc.GenericServerStream[ImpactAnalysisRequest, ImpactAnalysisEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RetrievalEngine_ImpactAnalysisServer = grpc.ServerStreamingServer[ImpactAnalysisEvent]

func _RetrievalEngine_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalEngineServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalEngine_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalEngineServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalEngine_ExpandNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalEngineServer).ExpandNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalEngine_ExpandNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalEngineServer).ExpandNeighbors(ctx, req.(*ExpandNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrievalEngine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalEngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrievalEngine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalEngineServer).Health(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RetrievalEngine_ServiceDesc is the grpc.ServiceDesc for RetrievalEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrievalEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eci.retrieval.v1.RetrievalEngine",
	HandlerType: (*RetrievalEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HybridSearch",
			Handler:    _RetrievalEngine_HybridSearch_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _RetrievalEngine_GetNode_Handler,
		},
		{
			MethodName: "ExpandNeighbors",
			Handler:    _RetrievalEngine_ExpandNeighbors_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RetrievalEngine_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImpactAnalysis",
			Handler:       _RetrievalEngine_ImpactAnalysis_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eci/retrieval/v1/retrieval.proto",
}
