# generated by datamodel-codegen:
#   filename:  hybrid-graph.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class DomainEnum(StrEnum):
    code = "code"
    doc = "doc"
    legal = "legal"
    compliance = "compliance"
    contract = "contract"


class Sha256(RootModel[constr(pattern=r"^[a-f0-9]{64}$")]):
    root: constr(pattern=r"^[a-f0-9]{64}$")


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    repo: str
    tenant_id: constr(min_length=1) | None = None
    acl_group: constr(min_length=1) | None = None
    commit_sha: constr(pattern=r"^[a-f0-9]{7,40}$")
    path: str
    start_line: conint(ge=0) | None = None
    end_line: conint(ge=0) | None = None
    ingested_at: AwareDatetime
    source_system: str | None = None


class Versioning(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    version: conint(ge=1)
    is_current: bool
    valid_from: AwareDatetime | None = None
    valid_to: AwareDatetime | None = None
    supersedes: str | None = None


class EmbeddingRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vector_id: str
    model_id: str
    dim: conint(ge=1)
    logic_fingerprint: Sha256 | None = None


class NodeType(StrEnum):
    File = "File"
    Module = "Module"
    Package = "Package"
    Class = "Class"
    Interface = "Interface"
    Method = "Method"
    Function = "Function"
    Parameter = "Parameter"
    Field = "Field"
    CallSite = "CallSite"


class Visibility(StrEnum):
    public = "public"
    private = "private"
    protected = "protected"
    internal = "internal"


class CodeExtension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node_type: NodeType
    language: str | None = None
    signature: str | None = None
    visibility: Visibility | None = None
    symbol_id: str | None = Field(None, description="SCIP / stack-graphs symbol id")
    doc_hash: Sha256 | None = None


class NodeType1(StrEnum):
    Document = "Document"
    Section = "Section"
    Paragraph = "Paragraph"


class DocExtension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node_type: NodeType1
    title: str | None = None
    mime_type: str | None = None


class NodeType2(StrEnum):
    Contract = "Contract"
    Clause = "Clause"
    Policy = "Policy"
    Regulation = "Regulation"


class ObligationLevel(StrEnum):
    mandatory = "mandatory"
    recommended = "recommended"
    prohibited = "prohibited"


class LegalExtension(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node_type: NodeType2
    jurisdiction: str | None = None
    effective_date: date | None = None
    obligation_level: ObligationLevel | None = None


class CodeNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(pattern=r"^[A-Za-z0-9_.:/#-]+$")
    domain: DomainEnum
    name: str
    ast_hash: Sha256
    content_hash: Sha256 | None = None
    embedding: EmbeddingRef | None = None
    provenance: Provenance
    versioning: Versioning
    ext: dict[str, Any] | None = None


class RelType(StrEnum):
    CALLS = "CALLS"
    IMPORTS = "IMPORTS"
    EXTENDS = "EXTENDS"
    IMPLEMENTS = "IMPLEMENTS"
    CONTAINS = "CONTAINS"
    DEPENDS_ON = "DEPENDS_ON"
    REFERENCES = "REFERENCES"
    OVERRIDES = "OVERRIDES"
    DERIVED_FROM = "DERIVED_FROM"
    GOVERNED_BY = "GOVERNED_BY"
    CITES = "CITES"


class CodeRelation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    domain: DomainEnum
    rel_type: RelType
    from_id: str
    to_id: str
    weight: float | None = None
    provenance: Provenance | None = None
    versioning: Versioning | None = None


class EnterpriseCodeIntelligenceAgnosticGraphEntities(
    RootModel[CodeNode | CodeRelation]
):
    root: CodeNode | CodeRelation = Field(
        ..., title="Enterprise Code Intelligence - Agnostic Graph Entities"
    )
