# generated by datamodel-codegen:
#   filename:  outbox-event.json

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class AggregateType(StrEnum):
    CodeNode = "CodeNode"
    CodeRelation = "CodeRelation"
    CodeChunk = "CodeChunk"
    CodeEmbedding = "CodeEmbedding"


class EventType(StrEnum):
    UPSERT = "UPSERT"
    DELETE = "DELETE"


class OutboxEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    aggregate_type: AggregateType
    aggregate_id: str
    event_type: EventType
    payload: dict[str, Any]
    created_at: AwareDatetime
    trace_id: str | None = None
