# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eci_core.retrieval.v1 import retrieval_pb2 as retrieval_dot_v1_dot_retrieval__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrieval/v1/retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalEngineStub:
    """============================================================
    SERVICE
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HybridSearch = channel.unary_unary(
                '/eci.retrieval.v1.RetrievalEngine/HybridSearch',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.ImpactAnalysis = channel.unary_stream(
                '/eci.retrieval.v1.RetrievalEngine/ImpactAnalysis',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisEvent.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/eci.retrieval.v1.RetrievalEngine/GetNode',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.ExpandNeighbors = channel.unary_unary(
                '/eci.retrieval.v1.RetrievalEngine/ExpandNeighbors',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/eci.retrieval.v1.RetrievalEngine/Health',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RetrievalEngineServicer:
    """============================================================
    SERVICE
    ============================================================

    """

    def HybridSearch(self, request, context):
        """Ricerca ibrida grafo+vettoriale con fusione RRF (k=60). Idempotente:
        eleggibile a retry/hedging secondo la policy del canale.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImpactAnalysis(self, request, context):
        """Impact analysis con streaming server-side dei nodi impattati.
        Idempotente (sola lettura); la deadline propagata copre l'intero stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Lookup puntuale di un CodeNode (tool get_node).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandNeighbors(self, request, context):
        """Espansione tipizzata dei vicini (tool get_callers/get_callees/
        expand_dependencies, parametrizzati da edge_types + direction).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness/readiness con dettaglio delle gambe di retrieval.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HybridSearchRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.HybridSearchResponse.SerializeToString,
            ),
            'ImpactAnalysis': grpc.unary_stream_rpc_method_handler(
                    servicer.ImpactAnalysis,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisEvent.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.GetNodeRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.GetNodeResponse.SerializeToString,
            ),
            'ExpandNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandNeighbors,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HealthCheckRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eci.retrieval.v1.RetrievalEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eci.retrieval.v1.RetrievalEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalEngine:
    """============================================================
    SERVICE
    ============================================================

    """

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eci.retrieval.v1.RetrievalEngine/HybridSearch',
            retrieval_dot_v1_dot_retrieval__pb2.HybridSearchRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImpactAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eci.retrieval.v1.RetrievalEngine/ImpactAnalysis',
            retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.ImpactAnalysisEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eci.retrieval.v1.RetrievalEngine/GetNode',
            retrieval_dot_v1_dot_retrieval__pb2.GetNodeRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eci.retrieval.v1.RetrievalEngine/ExpandNeighbors',
            retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.ExpandNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eci.retrieval.v1.RetrievalEngine/Health',
            retrieval_dot_v1_dot_retrieval__pb2.HealthCheckRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
