// eci/semanticcache/v1/semanticcache.proto
// Contratto gRPC del Semantic Cache Service (SPEC-022, T2.3): cache
// chiave->valore keyed su ast_hash + logic_fingerprint + acl_scope (ADD
// Modulo 3 §2.6.3), a supporto di un futuro consumatore embedding/summary
// (T2.4/T5.5, non ancora esistente — vedi SPEC-022 §5 Non-goals).
// Versionamento: package versionato (v1); campi additivi only; nessun
// riuso di tag; campi deprecati marcati reserved (stesso principio di
// eci/retrieval/v1/retrieval.proto, SPEC-002).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eci/semanticcache/v1/semanticcache.proto

package semanticcachev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chiave di cache: quadrupla entity_id + ast_hash + logic_fingerprint +
// acl_scope (SPEC-022 §2, enforcement SPEC-058/ADR-0012).
// logic_fingerprint resta una stringa opaca fornita dal chiamante.
// acl_scope deve essere il fingerprint canonico dello scope autenticato: il
// server lo deriva dai metadata e richiede uguaglianza prima dello storage.
type CacheKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntityId         string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	AstHash          string                 `protobuf:"bytes,2,opt,name=ast_hash,json=astHash,proto3" json:"ast_hash,omitempty"`
	LogicFingerprint string                 `protobuf:"bytes,3,opt,name=logic_fingerprint,json=logicFingerprint,proto3" json:"logic_fingerprint,omitempty"`
	AclScope         string                 `protobuf:"bytes,4,opt,name=acl_scope,json=aclScope,proto3" json:"acl_scope,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheKey) Reset() {
	*x = CacheKey{}
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheKey) ProtoMessage() {}

func (x *CacheKey) ProtoReflect() protoreflect.Message {
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheKey.ProtoReflect.Descriptor instead.
func (*CacheKey) Descriptor() ([]byte, []int) {
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheKey) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CacheKey) GetAstHash() string {
	if x != nil {
		return x.AstHash
	}
	return ""
}

func (x *CacheKey) GetLogicFingerprint() string {
	if x != nil {
		return x.LogicFingerprint
	}
	return ""
}

func (x *CacheKey) GetAclScope() string {
	if x != nil {
		return x.AclScope
	}
	return ""
}

// Valore di cache: riferimento a embedding + summary, versionato dal
// modello che li ha prodotti. ttl_seconds = 0 significa nessuna scadenza.
type CacheValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmbeddingRef  string                 `protobuf:"bytes,1,opt,name=embedding_ref,json=embeddingRef,proto3" json:"embedding_ref,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	EmbeddingDim  uint32                 `protobuf:"varint,4,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheValue) Reset() {
	*x = CacheValue{}
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheValue) ProtoMessage() {}

func (x *CacheValue) ProtoReflect() protoreflect.Message {
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheValue.ProtoReflect.Descriptor instead.
func (*CacheValue) Descriptor() ([]byte, []int) {
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheValue) GetEmbeddingRef() string {
	if x != nil {
		return x.EmbeddingRef
	}
	return ""
}

func (x *CacheValue) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CacheValue) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CacheValue) GetEmbeddingDim() uint32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *CacheValue) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	Value         *CacheValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *GetResponse) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *CacheKey              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *CacheValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() *CacheKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() *CacheValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eci_semanticcache_v1_semanticcache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP(), []int{4}
}

var File_eci_semanticcache_v1_semanticcache_proto protoreflect.FileDescriptor

const file_eci_semanticcache_v1_semanticcache_proto_rawDesc = "" +
	"\n" +
	"(eci/semanticcache/v1/semanticcache.proto\x12\x14eci.semanticcache.v1\"\x8c\x01\n" +
	"\bCacheKey\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x19\n" +
	"\bast_hash\x18\x02 \x01(\tR\aastHash\x12+\n" +
	"\x11logic_fingerprint\x18\x03 \x01(\tR\x10logicFingerprint\x12\x1b\n" +
	"\tacl_scope\x18\x04 \x01(\tR\baclScope\"\xac\x01\n" +
	"\n" +
	"CacheValue\x12#\n" +
	"\rembedding_ref\x18\x01 \x01(\tR\fembeddingRef\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rembedding_dim\x18\x04 \x01(\rR\fembeddingDim\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\"W\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .eci.semanticcache.v1.CacheValueR\x05value\"v\n" +
	"\n" +
	"PutRequest\x120\n" +
	"\x03key\x18\x01 \x01(\v2\x1e.eci.semanticcache.v1.CacheKeyR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .eci.semanticcache.v1.CacheValueR\x05value\"\r\n" +
	"\vPutResponse2\xa5\x01\n" +
	"\rSemanticCache\x12H\n" +
	"\x03Get\x12\x1e.eci.semanticcache.v1.CacheKey\x1a!.eci.semanticcache.v1.GetResponse\x12J\n" +
	"\x03Put\x12 .eci.semanticcache.v1.PutRequest\x1a!.eci.semanticcache.v1.PutResponseBB\n" +
	"\x18com.eci.semanticcache.v1P\x01Z$eci/semanticcache/v1;semanticcachev1b\x06proto3"

var (
	file_eci_semanticcache_v1_semanticcache_proto_rawDescOnce sync.Once
	file_eci_semanticcache_v1_semanticcache_proto_rawDescData []byte
)

func file_eci_semanticcache_v1_semanticcache_proto_rawDescGZIP() []byte {
	file_eci_semanticcache_v1_semanticcache_proto_rawDescOnce.Do(func() {
		file_eci_semanticcache_v1_semanticcache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eci_semanticcache_v1_semanticcache_proto_rawDesc), len(file_eci_semanticcache_v1_semanticcache_proto_rawDesc)))
	})
	return file_eci_semanticcache_v1_semanticcache_proto_rawDescData
}

var file_eci_semanticcache_v1_semanticcache_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_eci_semanticcache_v1_semanticcache_proto_goTypes = []any{
	(*CacheKey)(nil),    // 0: eci.semanticcache.v1.CacheKey
	(*CacheValue)(nil),  // 1: eci.semanticcache.v1.CacheValue
	(*GetResponse)(nil), // 2: eci.semanticcache.v1.GetResponse
	(*PutRequest)(nil),  // 3: eci.semanticcache.v1.PutRequest
	(*PutResponse)(nil), // 4: eci.semanticcache.v1.PutResponse
}
var file_eci_semanticcache_v1_semanticcache_proto_depIdxs = []int32{
	1, // 0: eci.semanticcache.v1.GetResponse.value:type_name -> eci.semanticcache.v1.CacheValue
	0, // 1: eci.semanticcache.v1.PutRequest.key:type_name -> eci.semanticcache.v1.CacheKey
	1, // 2: eci.semanticcache.v1.PutRequest.value:type_name -> eci.semanticcache.v1.CacheValue
	0, // 3: eci.semanticcache.v1.SemanticCache.Get:input_type -> eci.semanticcache.v1.CacheKey
	3, // 4: eci.semanticcache.v1.SemanticCache.Put:input_type -> eci.semanticcache.v1.PutRequest
	2, // 5: eci.semanticcache.v1.SemanticCache.Get:output_type -> eci.semanticcache.v1.GetResponse
	4, // 6: eci.semanticcache.v1.SemanticCache.Put:output_type -> eci.semanticcache.v1.PutResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_eci_semanticcache_v1_semanticcache_proto_init() }
func file_eci_semanticcache_v1_semanticcache_proto_init() {
	if File_eci_semanticcache_v1_semanticcache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eci_semanticcache_v1_semanticcache_proto_rawDesc), len(file_eci_semanticcache_v1_semanticcache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eci_semanticcache_v1_semanticcache_proto_goTypes,
		DependencyIndexes: file_eci_semanticcache_v1_semanticcache_proto_depIdxs,
		MessageInfos:      file_eci_semanticcache_v1_semanticcache_proto_msgTypes,
	}.Build()
	File_eci_semanticcache_v1_semanticcache_proto = out.File
	file_eci_semanticcache_v1_semanticcache_proto_goTypes = nil
	file_eci_semanticcache_v1_semanticcache_proto_depIdxs = nil
}
