// eci/semanticcache/v1/semanticcache.proto
// Contratto gRPC del Semantic Cache Service (SPEC-022, T2.3): cache
// chiave->valore keyed su ast_hash + logic_fingerprint + acl_scope (ADD
// Modulo 3 §2.6.3), a supporto di un futuro consumatore embedding/summary
// (T2.4/T5.5, non ancora esistente — vedi SPEC-022 §5 Non-goals).
// Versionamento: package versionato (v1); campi additivi only; nessun
// riuso di tag; campi deprecati marcati reserved (stesso principio di
// eci/retrieval/v1/retrieval.proto, SPEC-002).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: eci/semanticcache/v1/semanticcache.proto

package semanticcachev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticCache_Get_FullMethodName = "/eci.semanticcache.v1.SemanticCache/Get"
	SemanticCache_Put_FullMethodName = "/eci.semanticcache.v1.SemanticCache/Put"
)

// SemanticCacheClient is the client API for SemanticCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Firma esattamente come da SPEC-022 §2 (Get prende CacheKey direttamente,
// non un wrapper GetRequest — asimmetrico rispetto a Put per costruzione
// dichiarata della SPEC, non un'incoerenza da correggere qui). SERVICE_SUFFIX/
// RPC_REQUEST_STANDARD_NAME/RPC_RESPONSE_STANDARD_NAME sono già escluse dal
// lint di modulo in contracts/buf.yaml per lo stesso motivo di
// eci.retrieval.v1 (SPEC-002).
type SemanticCacheClient interface {
	// Lookup per chiave esatta. hit=false (nessun errore) su cache miss
	// genuino; Redis irraggiungibile è un errore gRPC Unavailable esplicito,
	// mai un hit=false silenzioso (SPEC-022 §4).
	Get(ctx context.Context, in *CacheKey, opts ...grpc.CallOption) (*GetResponse, error)
	// Scrittura idempotente (stessa chiave -> sovrascrive il valore
	// precedente). TTL applicato nativamente da Redis (SET ... EX).
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type semanticCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticCacheClient(cc grpc.ClientConnInterface) SemanticCacheClient {
	return &semanticCacheClient{cc}
}

func (c *semanticCacheClient) Get(ctx context.Context, in *CacheKey, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, SemanticCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticCacheClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, SemanticCache_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticCacheServer is the server API for SemanticCache service.
// All implementations must embed UnimplementedSemanticCacheServer
// for forward compatibility.
//
// Firma esattamente come da SPEC-022 §2 (Get prende CacheKey direttamente,
// non un wrapper GetRequest — asimmetrico rispetto a Put per costruzione
// dichiarata della SPEC, non un'incoerenza da correggere qui). SERVICE_SUFFIX/
// RPC_REQUEST_STANDARD_NAME/RPC_RESPONSE_STANDARD_NAME sono già escluse dal
// lint di modulo in contracts/buf.yaml per lo stesso motivo di
// eci.retrieval.v1 (SPEC-002).
type SemanticCacheServer interface {
	// Lookup per chiave esatta. hit=false (nessun errore) su cache miss
	// genuino; Redis irraggiungibile è un errore gRPC Unavailable esplicito,
	// mai un hit=false silenzioso (SPEC-022 §4).
	Get(context.Context, *CacheKey) (*GetResponse, error)
	// Scrittura idempotente (stessa chiave -> sovrascrive il valore
	// precedente). TTL applicato nativamente da Redis (SET ... EX).
	Put(context.Context, *PutRequest) (*PutResponse, error)
	mustEmbedUnimplementedSemanticCacheServer()
}

// UnimplementedSemanticCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticCacheServer struct{}

func (UnimplementedSemanticCacheServer) Get(context.Context, *CacheKey) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSemanticCacheServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedSemanticCacheServer) mustEmbedUnimplementedSemanticCacheServer() {}
func (UnimplementedSemanticCacheServer) testEmbeddedByValue()                       {}

// UnsafeSemanticCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticCacheServer will
// result in compilation errors.
type UnsafeSemanticCacheServer interface {
	mustEmbedUnimplementedSemanticCacheServer()
}

func RegisterSemanticCacheServer(s grpc.ServiceRegistrar, srv SemanticCacheServer) {
	// If the following call panics, it indicates UnimplementedSemanticCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticCache_ServiceDesc, srv)
}

func _SemanticCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServer).Get(ctx, req.(*CacheKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticCache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticCacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticCache_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticCacheServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticCache_ServiceDesc is the grpc.ServiceDesc for SemanticCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eci.semanticcache.v1.SemanticCache",
	HandlerType: (*SemanticCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SemanticCache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _SemanticCache_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eci/semanticcache/v1/semanticcache.proto",
}
